name: image-build
description: performs a docker build an push
inputs:
  registry: 
    required: true
    description: docker registry
  image-name:
    required: true
    description: name of the docker image
  tags:
    required: true
    description: tags for the docker image, if not set, the tags are extracted from the metadata
  github-token:
    required: true
    description: github token
  dockerfile:
    required: false
    description: path to the dockerfile
    default: Dockerfile

runs:
  using: "composite"
  steps:
    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3

    - name: docker login
      uses: docker/login-action@v3.0.0
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: extract metadata for docker image
      uses: docker/metadata-action@v5.5.1
      id: image-meta
      with:
        images: ${{ inputs.registry }}/${{ inputs.image-name }}
        tags: ${{ inputs.tags }}

    - name: build and push docker image
      uses: docker/build-push-action@v5.2.0
      with:
        context: ./
        push: true
        file: 
        tags: ${{ steps.image-meta.outputs.tags }}
        file: ${{ inputs.dockerfile }}
