frontend:
  deployment:
    name: olympguide-frontend
    replicas: 1
    forceRedeploy: false
    image:
      pullSecret: github-token-secret ## Key for Service Account Secret on K8s
      repository: ghcr.io/olympguide/frontend/vue
      pullPolicy: Always
      tag: latest
    resources:
      requests:
        memory: "250Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    port: 8000
  service:
    name: olympguide-frontend
    port: 8000
    targetPort: 8000
  ingress:
    host: olympguide-frontend.pm4.init-lab.ch
    path: /
    pathType: Prefix
   
   
