name: Cypess-Test-Jasmin-Delete-Me
on:
  push:
    branches: [ "KAN-80-Cypress-Pipeline-aufsetzen" ]

env:
  # GENERAL
  BACKEND_DIRECTORY: OlympGuide
  # DOCKER env
  IMAGE_NAME: ${{ github.repository }}/webserver
  ORGANISATION: OlympGuide
  DOCKERFILE-PATH: Dockerfile.development

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend repository
        uses: actions/checkout@v4
        with:
          path: frontend

      - name: Checkout backend repository
        uses: actions/checkout@v4
        with:
          repository: OlympGuide/Backend
          path: backend

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Start services with Docker Compose
        run: docker-compose up -d backend db
        working-directory: ./backend

      - name: Wait for services to be ready
        run: sleep 160 # Adjust the wait time as necessary

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./frontend
          build: npm run build
          start: 'npm run cy:run'

      - name: Stop Docker Compose
        run: docker-compose down
        working-directory: ./backend
