name: Cypess-Test
on:
    push:
        branches: [ "KAN-80-Cypress-Pipeline-aufsetzen" ]
    

env:
  # GENERAL
  BACKEND_DIRECTORY: OlympGuide
  # DOCKER env
  IMAGE_NAME: ${{ github.repository }}/webserver
  ORGANISATION: OlympGuide
  DOCKERFILE-PATH: Dockerfile.development

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev
        
  prettier:
    needs: cypress-run
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Run Prettier
        uses: rutajdash/prettier-cli-action@v1.0.0
        with:
            config_path: ./.prettierrc.json
            file_pattern: "**/*.{js,ts,css}"
            
      # This step only runs if prettier finds errors causing the previous step to fail
      # This steps lists the files where errors were found
      - name: Prettier Output
        if: ${{ failure() }}
        shell: bash
        run: |
            echo "The following files are not formatted:"
            echo "${{steps.prettier-run.outputs.prettier_output}}"