
name: Cypess-Test-Jasmin-Delete-Me
on:
    push:
        branches: [ "KAN-56-Frontend-Testing" ]


env:
  # GENERAL
  BACKEND_DIRECTORY: OlympGuide
  # DOCKER env
  IMAGE_NAME: ${{ github.repository }}/webserver
  ORGANISATION: OlympGuide
  DOCKERFILE-PATH: Dockerfile.development

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev